.circleci/config.yml, README.md, buildpacks/npm/CHANGELOG.md, buildpacks/npm/README.md, buildpacks/npm/bin/build, buildpacks/npm/bin/detect, buildpacks/npm/buildpack.toml, buildpacks/npm/fixtures/package-json/engine-npm/6.0.0/package.json, buildpacks/npm/fixtures/package-json/engine-npm/6.14.x/package.json, buildpacks/npm/fixtures/package-json/engine-npm/6.x/package.json, buildpacks/npm/fixtures/package-json/package.json, buildpacks/npm/fixtures/package-json/scripts/build/package.json, buildpacks/npm/fixtures/package-json/scripts/heroku-postbuild/package.json, buildpacks/npm/fixtures/package-json/scripts/start/package.json, buildpacks/npm/fixtures/package-lock/package-lock.json, buildpacks/npm/fixtures/package-lock/package.json, buildpacks/npm/lib/build.sh, buildpacks/npm/lib/detect.sh, buildpacks/npm/lib/utils/env.sh, buildpacks/npm/lib/utils/json.sh, buildpacks/npm/lib/utils/log.sh, buildpacks/npm/mocks/npm/v5.7/bin/npm, buildpacks/npm/mocks/npm/v5/bin/npm, buildpacks/npm/mocks/npm/v6/bin/npm, buildpacks/npm/package.toml, buildpacks/npm/shpec/build_shpec.sh, buildpacks/npm/shpec/detect_shpec.sh
Adds the Node.js NPM buildpack from: https://github.com/heroku/nodejs-npm-buildpack
=> Add nodejs npm buildpack

README.md, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/README.md, buildpacks/yarn/bin/build, buildpacks/yarn/bin/detect, buildpacks/yarn/buildpack.toml, buildpacks/yarn/lib/build.sh, buildpacks/yarn/lib/detect.sh, buildpacks/yarn/lib/utils/env.sh, buildpacks/yarn/lib/utils/json.sh, buildpacks/yarn/package.toml, meta-buildpacks/nodejs/package.toml
Copy nodejs-yarn buildpack to metabuildpack: https://github.com/heroku/nodejs-yarn-buildpack.
=> Add nodejs yarn buildpack

meta-buildpacks/nodejs/CHANGELOG.md
Update CHANGELOG for this pr: https://github.com/heroku/buildpacks-node/pull/6.
=> update changelog for latest PR

buildpacks/nodejs/CHANGELOG.md, buildpacks/npm/CHANGELOG.md, buildpacks/yarn/CHANGELOG.md
Updates the date format of the buildpack CHANGELOGs to follow the format the automated release scripts will use.
=> Update dates format [changelog skip]

.circleci/config.yml, .github/scripts/release-workflow-package-push.sh, .github/scripts/release-workflow-prepare-pr.sh, .github/workflows/release.yml, buildpacks/nodejs/buildpack.toml, buildpacks/npm/buildpack.toml, buildpacks/typescript/buildpack.toml, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/buildpack.toml, common/meta-build.sh, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
We want to test our metabuildpacks with the added changes of unreleased buildpacks while releasing with the released versions of buildpacks.
=> test meta buildpack with unreleased changes

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml, buildpacks/typescript/CHANGELOG.md, buildpacks/typescript/buildpack.toml, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
Adds the licenses to all the buildpack.tomls and then makes changes to the CHANGELOGs
=> add licenses to buildpack.toml

buildpacks/yarn/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
Also updates Yarn CHANGELOG with my recent release.
=> Bump meta buildpack version for next release

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/bin/build, buildpacks/nodejs/lib/build.sh, buildpacks/nodejs/shpec/build_shpec.sh, buildpacks/npm/bin/build, buildpacks/npm/lib/build.sh, buildpacks/npm/mocks/node/v14/bin/node, buildpacks/npm/shpec/build_shpec.sh, buildpacks/typescript/bin/build, buildpacks/typescript/lib/build.sh, buildpacks/typescript/shpec/build_shpec.sh, buildpacks/yarn/bin/build, buildpacks/yarn/lib/build.sh
if node version changes, the cache should be cleared
=> Flush cache with version change

.circleci/config.yml
@schneems, this should do the git diff and exit properly
=> Improve shfmt complaints

.github/workflows/check_changelog.yml
And adjust the job name to be clearer.
Both for parity with the check implementation in other repos.
Refs GUS-W-9728468.
=> Add missing event types to Check Changelog check

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
- https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/193
GUS-W-9964160
=> Reverts using clusters for node functions

.github/scripts/release-workflow-package-push.sh, .github/workflows/release.yml
I have no way of testing this #yolo
=> Create buildpackage file and upload to Github release

buildpacks/nodejs-engine/buildpack.toml, buildpacks/npm/buildpack.toml, buildpacks/typescript/buildpack.toml, buildpacks/yarn/buildpack.toml, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs/buildpack.toml
=> Add links to buildpack homepage

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/inventory.toml, common/nodejs-utils/src/bin/list_versions.rs
This makes several releases of node available.
Resolves #223.
=> Update nodejs-engine inventory

.circleci/config.yml
https://github.com/buildpacks/pack/releases/tag/v0.25.0
https://github.com/buildpacks/pack/releases/tag/v0.26.0
GUS-W-11136285.
=> Update Pack to 0.26.0 in CI

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
Bump `sf-fx-runtime-nodejs` to `0.11.2`
=> Bump sf-fx-runtime-nodejs to 0.11.2

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
https://github.com/heroku/procfile-cnb/releases/tag/v2.0.0
https://github.com/heroku/procfile-cnb/compare/v1.0.2...v2.0.0
GUS-W-11816969.
=> Upgrade heroku/procfile to v2.0.0

.circleci/config.yml, Cargo.lock, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/layers/dist.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/src/function.rs, buildpacks/nodejs-function-invoker/src/layers/runtime.rs, buildpacks/nodejs-function-invoker/src/main.rs, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/nodebin_s3.rs, common/nodejs-utils/src/vrs.rs
https://github.com/heroku/libcnb.rs/releases/tag/v0.11.0
GUS-W-11817952.
=> Update libcnb, libcnb-test and libherokubuildpack to 0.11.0

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
Includes changes:
* https://github.com/forcedotcom/sf-fx-runtime-nodejs/compare/v0.14.0...v0.14.1
=> Update `sf-fx-runtime-nodejs` from 0.14.0 to 0.14.1

.github/workflows/inventory.yml
See [W-1266447](https://gus.lightning.force.com/a07EE00001MqjFdYAJ)
=> Fix inventory workflow

.github/workflows/inventory.yml
Generates a token from a GitHub app that can be used in automation tasks that create pull requests.
=> Create automated PR with token

buildpacks/nodejs-engine/CHANGELOG.md
#567 Didn't include all the newly added releases. Something is up with the automation.
=> Add missing versions to changelog

buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-pnpm-install/buildpack.toml, buildpacks/nodejs-yarn/buildpack.toml, buildpacks/npm/buildpack.toml, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/buildpack.toml
Related to https://github.com/heroku/languages-github-actions/pull/88
=> Rename CNB release metadata

common/nodejs-utils/src/bin/diff_versions.rs
Outputs the lists of added and removed distributions ordered by their versions.
=> Fix inventory update order

buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/src/cfg.rs, buildpacks/nodejs-corepack/tests/fixtures/corepack-template/package-lock.v10.json, buildpacks/nodejs-corepack/tests/fixtures/corepack-template/package-lock.v8.json, buildpacks/nodejs-corepack/tests/integration_test.rs, meta-buildpacks/nodejs/buildpack.toml
This PR provides the ability to use corepack to control the version of npm to install.
[W-14278473](https://gus.lightning.force.com/lightning/r/a07EE00001cGcjtYAC/view)
=> Adds support for using corepack with npm

buildpacks/nodejs-function-invoker/tests/fixtures/simple-function/package-lock.json, buildpacks/nodejs-function-invoker/tests/fixtures/simple-typescript-function/package-lock.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-explicit-runtime-dependency-js/package-lock.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-explicit-runtime-dependency-js/package.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-explicit-runtime-dependency-ts/package-lock.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-explicit-runtime-dependency-ts/package.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-implicit-runtime-dependency-js/package-lock.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-implicit-runtime-dependency-js/package.json, buildpacks/nodejs-function-invoker/tests/fixtures/with-implicit-runtime-dependency-ts/package-lock.json, meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs-function/package.toml
This will replace the bash-based npm buildpack currently used in Functions with the new libcnb-based one.
[W-13916486](https://gus.lightning.force.com/lightning/r/a07EE00001XxdMnYAJ/view)
=> Use the libcnb-based npm buildpack in Functions

.github/workflows/ci.yml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/node_runtime_metrics/metrics_collector.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/_cpu_and_memory_simulator.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/clustered_app.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/single_process_app.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/worker_threads_app.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/metrics.spec.cjs, buildpacks/nodejs-engine/src/layers/mod.rs, buildpacks/nodejs-engine/src/layers/node_runtime_metrics.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs, test_support/src/lib.rs
This is a rewrite of the [heroku-nodejs-plugin](https://github.com/heroku/heroku-nodejs-plugin) using Node Performance APIs instead of a C++ addon to obtain equivalent details about garbage collection and event loop usage.
[W-14591321](https://gus.lightning.force.com/a07EE00001fe15JYAQ), [Related](https://github.com/heroku/heroku-buildpack-nodejs/pull/1178/)
=> Node.js Runtime Metrics

buildpacks/nodejs-engine/CHANGELOG.md
=> Fixed the changelog to follow the Keep a Changelog spec properly

.github/workflows/inventory.yml
Related to #840. Forgot to update the automation script with:
- the new argument for the path to the target changelog
- removing the perl-based text substitution step
=> Fix Node.js inventory automation

common/bin/download-verify-npm-package
Fixes this comment https://github.com/heroku/buildpacks-nodejs/pull/1014/files#r1951525430
=> Track signature success

Cargo.lock, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-corepack/src/cmd.rs, buildpacks/nodejs-corepack/src/enable_corepack.rs, buildpacks/nodejs-corepack/src/errors.rs, buildpacks/nodejs-corepack/src/main.rs, buildpacks/nodejs-corepack/src/prepare_corepack.rs, buildpacks/nodejs-yarn/tests/integration_test.rs, common/nodejs-utils/src/package_json.rs
=> Update corepack buildpack output

Cargo.lock, buildpacks/nodejs-pnpm-install/Cargo.toml, buildpacks/nodejs-pnpm-install/src/cmd.rs, buildpacks/nodejs-pnpm-install/src/configure_pnpm_store_directory.rs, buildpacks/nodejs-pnpm-install/src/configure_pnpm_virtual_store_directory.rs, buildpacks/nodejs-pnpm-install/src/errors.rs, buildpacks/nodejs-pnpm-install/src/main.rs, buildpacks/nodejs-pnpm-install/tests/integration_test.rs
=> Update pnpm-install buildpack output

Cargo.lock, buildpacks/nodejs-yarn/Cargo.toml, buildpacks/nodejs-yarn/src/cmd.rs, buildpacks/nodejs-yarn/src/configure_yarn_cache.rs, buildpacks/nodejs-yarn/src/install_yarn.rs, buildpacks/nodejs-yarn/src/main.rs
=> Update yarn buildpack output

Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-pnpm-engine/Cargo.toml
Since the integration of these libraries was done at different times there are differences in versions specified by individual projects so this PR aligns them all to the same versions.
=> Update bullet_stream and fun_run

Cargo.lock, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/src/install_nodejs_function_runtime.rs, buildpacks/nodejs-function-invoker/src/main.rs, buildpacks/nodejs-function-invoker/tests/integration_test.rs
=> Update function invoker buildpack output

.gitattributes, Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/errors.rs, buildpacks/nodejs-engine/src/install_node.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_checksum_verification_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_download_http_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_installation_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_read_temp_file_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_tarball_prefix_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_temp_file_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___dist_layer_untar_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___inventory_parse_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___package_json_access_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___package_json_parse_error.snap, buildpacks/nodejs-engine/src/snapshots/errors___unknown_version_error.snap, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/error_handling.rs, common/nodejs-utils/src/lib.rs, test_support/src/lib.rs
This PR adds detailed and consistent error messages for the nodejs-engine buildpack + includes snapshot testing for the output.
=> Improve nodejs-engine errors

Cargo.lock, buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-corepack/src/enable_corepack.rs, buildpacks/nodejs-corepack/src/errors.rs, buildpacks/nodejs-corepack/src/main.rs, buildpacks/nodejs-corepack/src/prepare_corepack.rs, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_create_bin_directory_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_create_cache_directory_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_enable_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_package_manager_missing_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_prepare_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_version_command_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___corepack_version_parse_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___package_json_access_error.snap, buildpacks/nodejs-corepack/src/snapshots/errors___package_json_parse_error.snap, buildpacks/nodejs-engine/src/errors.rs, common/nodejs-utils/src/error_handling.rs
This PR adds detailed and consistent error messages for the corepack buildpack + includes snapshot testing for the output.
=> Improve corepack errors

Cargo.lock, buildpacks/nodejs-engine/src/errors.rs, buildpacks/nodejs-engine/src/snapshots/errors___unknown_version_error.snap, buildpacks/nodejs-npm-engine/CHANGELOG.md, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-engine/src/errors.rs, buildpacks/nodejs-npm-engine/src/install_npm.rs, buildpacks/nodejs-npm-engine/src/main.rs, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_inventory_parse_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_missing_npm_engine_requirement_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_node_version_command_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_node_version_parse_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_install_decompress_tarball_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_install_download_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_install_install_npm_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_install_open_tarball_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_install_remove_existing_npm_install_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_version_command_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_version_parse_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_npm_version_resolve_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_package_json_access_error.snap, buildpacks/nodejs-npm-engine/src/snapshots/errors___npm_engine_package_json_parse_error.snap, buildpacks/nodejs-npm-engine/tests/integration_test.rs
This PR adds detailed and consistent error messages for the npm engine buildpack + includes snapshot testing for the output.
=> Improve npm engine errors

Cargo.lock, buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-npm-install/src/configure_npm_cache_directory.rs, buildpacks/nodejs-npm-install/src/configure_npm_runtime_env.rs, buildpacks/nodejs-npm-install/src/errors.rs, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_application_error_missing_lockfile.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_application_error_multiple_lockfiles.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_build_script_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_detect_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_node_build_scripts_metadata_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_npm_install_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_npm_version_command_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_npm_version_parse_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_package_json_access_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_package_json_parse_error.snap, buildpacks/nodejs-npm-install/src/snapshots/errors___npm_install_set_cache_dir_error.snap, buildpacks/nodejs-npm-install/tests/integration_test.rs, common/nodejs-utils/src/application.rs
This PR adds detailed and consistent error messages for the npm install buildpack + includes snapshot testing for the output.
=> Improve npm install errors

Cargo.lock, buildpacks/nodejs-engine/tests/integration_test.rs, buildpacks/nodejs-engine/tests/snapshots/reinstalls_node_if_version_changes.snap, buildpacks/nodejs-engine/tests/snapshots/simple_indexjs.snap, buildpacks/nodejs-engine/tests/snapshots/simple_serverjs.snap, test_support/Cargo.toml, test_support/src/lib.rs, test_support/src/snapshot_filters.rs, test_support/src/test_arch.rs, test_support/src/test_builder.rs
=> Output snapshots for node-engine

buildpacks/nodejs-npm-engine/tests/integration_test.rs, buildpacks/nodejs-npm-engine/tests/snapshots/npm_engine_install.snap, buildpacks/nodejs-npm-engine/tests/snapshots/test_node_version_change_invalidates_npm_engine_cache.snap, buildpacks/nodejs-npm-engine/tests/snapshots/test_npm_engine_caching.snap, buildpacks/nodejs-npm-engine/tests/snapshots/test_npm_version_change_invalidates_npm_engine_cache.snap
=> Output snapshots for npm engine

buildpacks/nodejs-pnpm-engine/tests/integration_test.rs, buildpacks/nodejs-pnpm-engine/tests/snapshots/pnpm_unknown_version.snap
=> Output snapshots for pnpm engine

buildpacks/nodejs-corepack/tests/snapshots/corepack_yarn_2.snap, buildpacks/nodejs-corepack/tests/snapshots/corepack_yarn_3.snap, buildpacks/nodejs-yarn/tests/integration_test.rs, buildpacks/nodejs-yarn/tests/snapshots/test_default_web_process_registration_is_skipped_if_procfile_exists.snap, buildpacks/nodejs-yarn/tests/snapshots/test_native_modules_are_recompiled_even_on_cache_restore.snap, buildpacks/nodejs-yarn/tests/snapshots/test_skip_build_scripts_from_buildplan.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_1_typescript.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_2_modules_nonzero.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_2_pnp_zero.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_3_modules_zero.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_3_pnp_nonzero.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_4_modules_zero.snap, buildpacks/nodejs-yarn/tests/snapshots/yarn_4_pnp_nonzero.snap, test_support/src/snapshot_filters.rs
=> Output snapshots for Yarn

buildpacks/nodejs-pnpm-install/tests/integration_test.rs, buildpacks/nodejs-pnpm-install/tests/snapshots/pnpm_7_pnp.snap, buildpacks/nodejs-pnpm-install/tests/snapshots/pnpm_8_hoist.snap, buildpacks/nodejs-pnpm-install/tests/snapshots/pnpm_8_nuxt.snap, buildpacks/nodejs-pnpm-install/tests/snapshots/test_default_web_process_registration_is_skipped_if_procfile_exists.snap, buildpacks/nodejs-pnpm-install/tests/snapshots/test_native_modules_are_recompiled_even_on_cache_restore.snap, buildpacks/nodejs-pnpm-install/tests/snapshots/test_skip_build_scripts_from_buildplan.snap, test_support/src/lib.rs, test_support/src/snapshot_filters.rs
=> Output snapshots for pnpm install
