.github/scripts/release-workflow-package-push.sh, .github/scripts/release-workflow-prepare-pr.sh, .github/workflows/release.yml, buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml, buildpacks/typescript/CHANGELOG.md, buildpacks/typescript/buildpack.toml, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
Port of https://github.com/heroku/buildpacks-jvm/pull/16
TODO:
=> Add automated post-release PRs workflow

.circleci/config.yml, .github/scripts/release-workflow-package-push.sh, .gitignore, README.md, common/meta-build.sh, common/rsync-build.sh, meta-buildpacks/nodejs/build.sh
Port of https://github.com/heroku/buildpacks-jvm/pull/19, see that PR for a detailed description.
This adds a build script to the meta buildpack, individual buildpack scripts need to be added separately if required.
=> Port build script support from buildpacks-jvm

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/bin/build, buildpacks/nodejs/lib/build.sh, buildpacks/nodejs/shpec/build_shpec.sh
In order to make node modules available downstream, copy the path into the build ENV for subsequent buildpacks.
=> copy node modules dir path into env

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/bin/detect, buildpacks/nodejs/lib/detect.sh, buildpacks/nodejs/shpec/detect_shpec.sh
Remove package.json requirement to fix downstream buildpack issues for builds that need the Node runtime, but that may not have a package.json.
=> remove package.json requirement

.circleci/config.yml
Uncomment out the failing test from yesterday. Circle CI support suggested setting the Docker version, but it seems the test is fixed without doing that.
=> Readd heroku-18 test

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
pack-images already has 0.2.0 as meta buildpack version, so this bumps the minor version up to 0.3.0.
=> bump version so it does not collide with the pack-images meta buildpack

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/lib/build.sh, buildpacks/npm/CHANGELOG.md, buildpacks/npm/lib/build.sh, buildpacks/typescript/CHANGELOG.md, buildpacks/typescript/lib/build.sh, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/lib/build.sh, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
Fixes stack image detect to clear cache when `store.toml` is stored then retrieved. It will trim the whitespace around the string when grepping from the `store.toml`.
Also updates Procfile CNB version to pull in updated logging styles.
=> Fix stack image detect

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/package.toml
Update the metabuildpacks to reference `procfile-cnb` from their tags instead of the sha, so there isn't sha conflicts with other buildpacks downstream.
Possibly related to: https://github.com/buildpacks/pack/issues/1081
=> update the metabuildpacks to use procfile-cnb tag

meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/README.md, meta-buildpacks/nodejs-function/build.sh, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs-function/package.toml
Once the new invoker is ready and has its own buildpack, we will remove all except 'heroku/nodejs' and the upcoming invoker buildpack from buildpack.toml; its name will not be 'heroku/node-function-buildpack' or similar, but probably 'salesforce/nodejs-function-invoker', just like JVM has it.
=> initial move of nodejs-function related order group from pack-images/evergreen_fn

.circleci/config.yml, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs-function/package.toml, test/meta-buildpacks/nodejs-function/build.sh, test/meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs-function/package.toml
Ticket:
https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH0000008mOuYAI/view
The "regular" nodejs metabuildpack is already tested under test/meta-buildpack/nodejs. This adds local files to ensure that the functions metabuildpack can be built without errors.
=> Add tests to the nodejs-function meta-buildpack

meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs-function/package.toml, test/meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs-function/package.toml
This updates the `heroku/nodejs-function` metabuildpack to replace the Riff-based buildpack dependencies with `heroku/nodejs-function-invoker`.
This change is separate from #47, since it depends on that PR being merged and the new buildpack published, so that we have the ECR image URL for use by the metabuildpack.
Closes GUS-W-9228226.
=> Update heroku/nodejs-function to use heroku/nodejs-function-invoker

.circleci/config.yml, meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs-function/buildpack.toml
Fixes for #48:
Those were using the versions of the next release, most likely copied from the test meta-buildpack. I also updated the CircleCI config to package this buildpack which would have prevented this issue.
=> Fix nodejs-function dependency versions

buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/lib/build.sh
There's a bug where if the nodejs.toml doesn't exist, the build will fail, so this checks to see if there's a file before it reads the file. (Bug fix for the initial build)
=> check for presence of nodejs.toml before reading for clearing cache

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/lib/build.sh, buildpacks/nodejs-function-invoker/shpec/build_shpec.sh
Newer versions of the function runtime require a different startup command.
=> Fix Node.js function runtime startup command

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/lib/build.sh
Previously the runtime package tarball was left behind in the runtime layer after the package was installed, so ended up in the built image.
Now the file is downloaded to a temporary directory instead of the layer, and cleaned up after the npm install.
The `local runtime_package` statement being on a separate line is required due to:
https://github.com/koalaman/shellcheck/wiki/SC2155#problematic-code-in-the-case-of-local
Closes GUS-W-9238585.
=> function-invoker: Clean up runtime download after install

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/lib/build.sh, buildpacks/nodejs-function-invoker/shpec/build_shpec.sh
Buildpack API 0.6 and above requires that buildpacks mark at least one process type as default, otherwise there will be no default process set:
https://github.com/buildpacks/spec/releases/tag/platform%2Fv0.6
https://github.com/buildpacks/rfcs/blob/main/text/0064-buildpacks-contribute-default-process-type.md
The Node.js invoker buildpack is using API 0.6 (compared to some of the other buildpacks that are using older API versions), so needs the default process declared explicitly, to prevent errors at runtime.
Closes GUS-W-9260453.
=> function-invoker: Mark the web process as default

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/bin/build, buildpacks/nodejs-function-invoker/lib/build.sh, buildpacks/nodejs-function-invoker/opt/run.sh, buildpacks/nodejs-function-invoker/shpec/build_shpec.sh
Now when the `DEBUG_PORT` env var is set, Node is started with debugger support enabled:
https://nodejs.org/en/docs/guides/debugging-getting-started/
This is based on the approach taken by the JVM invoker buildpack:
https://github.com/heroku/buildpacks-jvm/pull/85
https://github.com/heroku/buildpacks-jvm/pull/93
Closes GUS-W-9260143.
=> Add support for remote debugging via DEBUG_PORT

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/opt/run.sh
If `DEBUG_PORT` is defined, but `NODE_OPTIONS` was not already set, the functions invocation would fail with:
```
...
Running on port :8080
Debugger running on port :9229
/layers/heroku_nodejs-function-invoker/opt/run.sh: line 9: NODE_OPTIONS: unbound variable
```
I would add a test, however we only have unit tests, and it's very hard to test the `run.sh` wrapper given `sf-fx-runtime-nodejs` is not installed during the unit tests. Cutlass tests are likely the answer to this in the future.
Follow-up to #59.
Refs GUS-W-9260143.
=> function-invoker: Fix unbound variable error when using DEBUG_PORT

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/bin/detect, buildpacks/nodejs-function-invoker/lib/utils/download.sh
Installs yj before the detect script runs, so that the correct files can be parsed in the function invoker buildpack.
=> install yj before detect script

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/bin/detect, buildpacks/nodejs-function-invoker/lib/utils/download.sh
The path name was incorrect, so adding this to update and we should add a ticket for testing bin scripts in CI!
Testing this build locally to make sure the functions build passes.
=> Reference correct path with importing download.sh

.circleci/config.yml, .gitignore, .rspec, Gemfile, Gemfile.lock, test/fixtures/simple-function/.eslintrc, test/fixtures/simple-function/.mocharc.json, test/fixtures/simple-function/index.js, test/fixtures/simple-function/package.json, test/fixtures/simple-function/project.toml, test/specs/node-function/cutlass/function_spec.rb, test/specs/node-function/spec_helper.rb
- Adds the cutlass library github.com/heroku/cutlass for automating scripting of building buildpacks via pack in tests. 
- Sets up rspec and related helper libraries to  allow writing tests in Ruby
- Adds a "simple" node app that contains a function, it returns a string of "hello world"
- Adds a test in rspec that uses cutlass to first build the node function buildpack, then it builds the "simple" node app using the node function buildpack and makes assertions on the output. Once the build is complete, the app is booted via docker and a function request completes successfully.
=> Test node function interface via Cutlass

.circleci/config.yml, buildpacks/nodejs/CHANGELOG.md, buildpacks/nodejs/lib/build.sh, test/specs/node/cutlass/basic_spec.rb, test/specs/node/spec_helper.rb
It was noted that if an app tries to deploy using Node 16 and then tries to deploy the same app using Node 14 it fails. It turns out it will fail for any node version change and not just a downgrade in version.
```
ERROR: failed to build: Near line 10 (last key parsed ''): Key 'metadata' has already been defined.
```
The reason for this error is that the nodejs.toml file contains metadata key twice which makes it invalid tool and pack cannot process it. Here's what the contents:
```
build = true
launch = true
cache = true
[metadata]
version = "16.3.0"
cache = true
build = true
launch = true
[metadata]
version = "14.17.0"
```
The fix is to write over the toml file instead of appending to it. I'm worried though there may be other places with a similar bug such as installing yarn. 
There are …
=> Allow app to change Node Versions

buildpacks/npm/CHANGELOG.md, buildpacks/typescript/CHANGELOG.md, buildpacks/yarn/CHANGELOG.md
In #40 a change was made to multiple buildpacks, however a changelog entry was only added for `heroku/nodejs-engine`.
This adds the remaining changelog entries.
It also switches back to the keepachangelog.com format (eg using "Fixed" headings etc).
Closes GUS-W-9469704.
=> Add missing changelog entries for npm/yarn/typescript buildpacks

test/specs/node/cutlass/basic_spec.rb
Since currently it's using the standard (non-test) metabuildpack, which causes failures when the versions are bumped in #87.
I was not able to use the `:default` alias (to avoid specifying the default test metabuildpack again directly),  since the current `spec_helper.rb` `Cutlass::LocalBuildpack` teardown doesn't work correctly with multiple tests using the default buildpack.
Follow-up to #86.
[skip changelog]
Refs GUS-W-9481665.
=> yarn: Make Cutlass test use the test metabuildpack

test/specs/node-function/spec_helper.rb, test/specs/node/spec_helper.rb
Previously the Node Cutlass tests were using the Heroku-18 based builder image instead, which is not the default on the platform.
In addition, I've fixed a variable name in `spec_helper.rb` for the non-functions test. This was presumably a copy-paste error when creating the tests.
Closes GUS-W-9483311.
=> Tests: Run Cutlass tests with the Heroku-20 based builder image

.circleci/config.yml, .gitignore, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, test/fixtures/simple-typescript-function/.eslintrc, test/fixtures/simple-typescript-function/.mocharc.json, test/fixtures/simple-typescript-function/index.ts, test/fixtures/simple-typescript-function/package.json, test/fixtures/simple-typescript-function/project.toml, test/fixtures/simple-typescript-function/tsconfig.json, test/specs/node-function/cutlass/function_spec.rb
Version 0.1.2-ea of sf-fx-runtime-nodejs fom: https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/61 is needed to fix a problem where types were not properly exported for typescript support. This enables cutlass integration tests to run:
- Release sf-fx-runtime-nodejs work item W-9590917 https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000Qz69YAC/view
- Cutlass test for typescript work item W-9424162: https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07AH000000OAyJYAW/view
This PR introduces a test app `simple-typescript-function` that contains necessary files to activate the typescript support of this project https://github.com/heroku/buildpacks-nodejs/blob/53ac19086d0959c50e3d97128d62760816e753f4/buildpacks/typescript/lib/detect.sh.
The ultimate purpose of …
=> Bump sf-fx-runtime-nodejs to 0.1.2-ea and Typescript function integration test

meta-buildpacks/nodejs-function/CHANGELOG.md, test/meta-buildpacks/nodejs-function/buildpack.toml
Currently the nodejs-function test meta-buildpack has the same buildpack ID as the actual nodejs-function meta-buildpack, causing the publishing script to publish it instead of the intended buildpack.
The publishing script is being updated in another PR (#103) to fail if duplicate buildpack IDs are found, so we must give the test buildpack a unique ID.
The new name suffix matches the style used for the test nodejs (non-function) meta-buildpack and also all of the JVM test meta-buildpacks.
I've also changed the test meta-buildpack version to `0.0.0` for parity with the other test buildpacks.
Fixes GUS-W-9672962.
=> Use a unique buildpack ID for the test nodejs-function buildpack

.github/scripts/release-workflow-package-push.sh
Previously if duplicate buildpack IDs existed in the repository, the publish script would publish the first buildpack found, and exit 0.
The Node.js test buildpacks have the same IDs as the real buildpacks, leading to the test buildpacks being published instead of the intended buildpack.
With this change, the publish script now traverses the repository and errors if more than one buildpack with the same ID was found.
In addition, I've added a bit more logging around the name/path/version of the found buildpack, which would have aided debugging this issue.
This PR is the Node.js equivalent of:
https://github.com/heroku/buildpacks-jvm/pull/129
Refs GUS-W-9672962.
=> Make publishing script fail if duplicate buildpack IDs found

.github/dependabot.yml
See:
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates#supported-repositories-and-ecosystems
Whilst this repository isn't using Rust right now, it will be shortly, so I've enabled Cargo updates now to save churn.
I've also changed the frequency to daily, so we don't have to wait as long.
Refs GUS-W-9678950.
=> Enable Dependabot for GitHub Actions and Cargo

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs-function/buildpack.toml
This upgrades the sf-fx-runtime-nodejs to 0.4.0. It also bumps the minor version of the nodejs-function-invoker buildpack since we're adding new functionality.
This brings in https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/99, adding support for ESM / JavaScript Modules.
=> Bump sf-fx-runtime-nodejs to 0.4.0 in nodejs-function-invoker

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
Update [runtime](https://github.com/forcedotcom/sf-fx-runtime-nodejs) to [0.5.2](https://github.com/forcedotcom/sf-fx-runtime-nodejs/releases/tag/v0.5.2).
Changes:
- Handle malformed/missing cloud event salesforce extension ([#141](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/141))
- Update package name to @heroku/sf-fx-runtime-nodejs ([#139](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/139))
- Automatically expand ReferenceIDs with `.toApiString()` ([#133](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/133))
- Add unit testing for src/index.ts ([#118](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/118))
- Utilize @salesforce/core for logging with logfmt ([#119](https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/119))
=> update runtime to new version

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
- Updates SFDC API version to 0.5.3 https://github.com/forcedotcom/sf-fx-runtime-nodejs/blob/main/CHANGELOG.md#070---2021-09-29
=> Update sf-fx-runtime-nodejs to 0.7.0

.github/scripts/release-workflow-package-push.sh, .github/scripts/release-workflow-prepare-pr.sh
Currently if you attempt to release a buildpack with id `heroku/nodejs   ` (with whitespace before or after) it will fail. It also takes a few minutes to fail and isn't 100% obvious in the message that the failure is due to whitespace.
This trims whitespace from the input on both release scripts. I also modified the error message to quote the variable so if it's used in the future without being trimmed first, the error would be easier to detect.
Other considerations:
- Could we trim the input earlier? Ideally not having to do this in every script would be ideal.
- It takes a long time running on actions before this will execute, we should check the input build pack id early and fail early to give fast feedback in the future.
- These scripts are not tested and should be modified with …
=> Trim whitespace on release build pack

Gemfile.lock, test/fixtures/simple-function/index.js, test/specs/node-function/cutlass/function_spec.rb
Currently, there are no integration tests that ensure the contents to the log interface show up in the output. This commit ensures basic logging functionality does not regress.
GUS-W-9933414
Java logging test: https://github.com/heroku/buildpacks-jvm/pull/175
Node logging test: https://github.com/heroku/buildpacks-nodejs/pull/135
=> Add test for logging output

buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/bin/build, buildpacks/yarn/buildpack.toml, buildpacks/yarn/lib/build.sh
Buildpack API 0.6 requires the `launch`, `cache`, and `build` keys to be under the `[types]` table.
=> Fix yarn install and upgrade to Buildpack API 0.6

.github/scripts/release-workflow-package-push.sh
We're failing to build the buildpackage during release: https://github.com/heroku/buildpacks-nodejs/runs/4168800227?check_suite_focus=true. The filename of `heroku/nodejs-yarn` is problematic, since it has a slash.
This error started with the release of #160.
=> Fix buildpackage filename (drop the slash)

.github/scripts/release-workflow-package-push.sh, buildpacks/yarn/buildpack.toml, test/meta-buildpacks/nodejs/buildpack.toml
The latest release action failed: https://github.com/heroku/buildpacks-nodejs/runs/4170762218?check_suite_focus=true. The `git clean` step was removing the buildpackage. This PR puts buildpackage in a tmp dir, so it's not effected by git clean.
heroku/nodejs-yarn@0.1.7 has been yanked ([here](https://github.com/buildpacks/registry-index/issues/2151)) since it did not publish correctly. I'm bumping the version to 1.8 because we can't republish over yanked buildpacks.
=> Fixup buildpackage release

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
This updates the nodejs invoker/runtime to 0.9.2. There are only minor changes described here: https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/266.
GUS-W-10379120
=> Bump invoker to 0.9.2

.circleci/config.yml
Packaging the buildpack repeats endlessly in CI if it fails. There is a counter, but it never gets incremented. Let's fix that.
=> Increment counter when failing to package

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/bin/build, buildpacks/nodejs-engine/lib/build.sh, buildpacks/nodejs-engine/shpec/build_shpec.sh, buildpacks/npm/CHANGELOG.md, buildpacks/npm/lib/build.sh
In the scenario where a TypeScript app build has the correct Node.js version cached, but something in the `package.json` or `package-lock.json` has changed causing the `node_modules` cache to be invalid, that build would fail with `tsc: not found`. 
On a build without any cache, TypeScript builds would pass. But this may have been accidental. We were creating a `env.build/NODE_ENV.override` file, but we'd unintentionally delete it a short time later with a `rm -rf` during `install_or_reuse_node()`. Since `NODE_ENV` was unset, that meant that `npm ci` and/or `npm install` would install all `devDependencies`, including `typescript`.
On a build with a valid `nodejs` cache, the `rm -rf` mentioned never happens. So, for these builds `NODE_ENV` is set to `production` during `npm ci` or `npm …
=> Fix `tsc: not found` for typescript rebuilds

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
Updates sf-fx-runtime-nodejs to 0.11.0. The primary change included in this release is https://github.com/forcedotcom/sf-fx-runtime-nodejs/pull/294.
[GUS-W-10728741](https://gus.my.salesforce.com/a07EE00000qUu23YAC)
=> Update to sf-fx-runtime-nodejs 0.11.0

.github/workflows/release.yml
The release buildpack script is failing for rust based buildpacks: https://github.com/heroku/buildpacks-nodejs/actions/runs/1959345733.
We need to install musl-tools, rust, and libcnb-cargo so that we can build/release the libcnb-based buildpacks like `heroku/nodejs-engine` that was introduced in #184.
This code was lifted from https://github.com/heroku/buildpacks-jvm/blob/main/.github/workflows/release.yml#L31-L44
GUS-W-10729118
=> Install musl tools, rust, and libcnb-cargo prior to release

buildpacks/npm/CHANGELOG.md, buildpacks/npm/lib/build.sh, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/lib/build.sh
In #184, we updated the buildpack api version for `heroku/npm` to `0.6`. This had the unintended side effect of the `web` process no longer being flagged as a default process. In earlier buildpack API versions, overwriting a default process with an undefined default would result in a process flagged as default. Newer buildpack API versions will prefer the default setting of the overwriting process.
This PR ensures the `web` process affiliated with `package.json`'s `scripts.start` is flagged as a default process, for both `yarn` and `npm`. 
Fixes #211 
[W-10888625](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000tVabFYAS)
=> Set package.json scripts.start as a default process

buildpacks/nodejs-engine/CHANGELOG.md, common/nodejs-utils/src/package_json.rs, test/fixtures/node-with-indexjs/package.json, test/fixtures/node-with-serverjs/package.json
=> package.json version now optional

common/nodejs-utils/src/inv.rs, common/nodejs-utils/src/nodebin_s3.rs
To let others create an inventory.toml, I'd like to make `etag` optional. From what I can tell this is just an artifact of nodebin using S3. It's not being used anywhere in the buildpack. I wonder if we should even remove this.
=> make etag optional part of the inventory

.circleci/config.yml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
The new libcnb.rs `heroku/procfile` is ready to go. Let's use it!
[W-10475648](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000hwHhMYAU)
=> Update heroku/procfile to 1.0.0

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
Version 1.0.0 of `heroku/procfile` can cause build failures on older versions of `pack`. More details here: https://github.com/heroku/procfile-cnb/pull/55
[W-10475648](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000hwHhMYAU)
=> Bump heroku/procfile to 1.0.1

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml, buildpacks/yarn/CHANGELOG.md, buildpacks/yarn/buildpack.toml
This PR revises stack support for all buildpacks. It adds explicit support for `heroku-22` on all buildpacks, and additionally:
- Drops support for `bionic` for the `heroku/nodejs-function-invoker` (this buildpack doesn't make sense on other stacks)
- Adds wildcard stack support for `heroku/nodejs-npm` to match `heroku/nodejs-yarn` (this buildpack should be useable in most places `node` and/or `npm` is available)
[W-10345122](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000ZZE8oYAH)
=> Add support for the heroku-22 stack

.github/workflows/inventory.yml
In #235, there were no new node versions, but we opened a PR anyway. The change (added `-`) to the changelog triggered a PR to be opened.
This PR uses `xargs` to avoid touching the changelog when there is no diff message.
[W-10942589](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000uDs1SYAS)
=> Fix inventory automation when there are no changes

.circleci/config.yml
We support heroku-22, so we should test against it.
[W-10343872](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00000ZVsEZYA1)
=> Add buildpacks:22 to the test matrix

.circleci/config.yml, Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-function-invoker/Cargo.toml, common/nodejs-utils/Cargo.toml
This updates `rust`, `libcnb`, and `libherokubuildpack`. It also includes a complete rebuild of `Cargo.lock`.
Supersedes #247, #248.
=> Update rust, libcnb, libherokubuildpack

.github/workflows/release.yml
Since `PUBLIC_REPO_TOKEN` doesn't mention GitHub, and the "repo" part of the name could also be relating to Docker Hub or ECR repositories.
I've not used the name `GITHUB_TOKEN`, since for GitHub Actions there is already an env var of that name provided automatically. That env var isn't suitable for publishing CNB releases, since we need to open an issue against the upstream CNB registry's index repo to trigger a release, whereas the GH Actions provided token only gives access to the repository where the action ran.
GUS-W-11031533.
=> Rename `PUBLIC_REPO_TOKEN` to `CNB_REGISTRY_RELEASE_BOT_GITHUB_TOKEN`

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/inventory.toml, common/nodejs-utils/src/inv.rs, common/nodejs-utils/src/nodebin_s3.rs
S3 URLs where the bucket name is part of the URL path are deprecated.
Instead, it's recommended to use the virtual-hosted style references, where the bucket name is part of the domain. 
The latter allows AWS to use DNS to direct requests directly to the appropriate region's S3 endpoint, rather than having to route via the global S3 endpoint (which AWS describe as being a single point of failure/harder to scale etc).
There is a small chance this may also help with some of the S3 reliability issues seen in [heroku/builder](https://github.com/heroku/builder) Circle CI runs - however even if it doesn't, at least we'll no longer be using the deprecated URLs/endpoints.
See:
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ …
=> Switch away from deprecated path-based S3 URLs

Cargo.lock, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/src/main.rs, buildpacks/nodejs-function-invoker/tests/integration_test.rs
Updates this buildpack to `libcnb` `0.8.0` and `libcnb-test` `0.4.0`. Some minor code changes were required due to breaking changes. 
This buildpack was using some custom exit codes. Custom exit codes are no longer supported due to issues making them work regardless of when an error occured. @joshwlewis, @colincasey, is this a deal-breaker for you or did you add them because the framework forced you to?
Closes GUS-W-11342069
=> Upgrade to libcnb 0.8.0

Cargo.lock, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-function-invoker/src/main.rs
Update `libcnb` and `libherokubuildpack` to `0.10.0` and therefore to buildpack API `0.8` as well.
Closes GUS-W-11680342
=> Update libcnb to 0.10.0

common/nodejs-utils/src/inv.rs
Previously it wasn't possible to compile the Rust parts of the buildpack on ARM64 (such as when using an M1 Macbook), since the compile failed with:
```
error[E0425]: cannot find value `ARCH` in this scope
--> common/nodejs-utils/src/inv.rs:45:45
|
45 |         let platform = format!("{}-{}", OS, ARCH);
|                                             ^^^^ not found in this scope
|
help: consider importing this constant
|
1  | use std::env::consts::ARCH;
|
```
This makes contributing to the buildpack from an M1 machine frustrating, since one has to comment out the architecture conditional every time, then remember not to include it in the commit with the other changes.
At such time as the Node.js buildpack fully supports ARM64 Docker images, conditionals can be added back with the …
=> Fix compilation of buildpack on ARM64

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
This will make all the changes listed in https://github.com/forcedotcom/sf-fx-runtime-nodejs/blob/main/CHANGELOG.md#0120---2022-09-28 available.
GUS-W-11543492
=> Bump sf-fx-runtime-nodejs to 0.12.0

.github/workflows/release.yml
I noticed this in the https://github.com/heroku/buildpacks-jvm repository. It looks like the default token permissions have been overridden by an org-wide policy. This change restores the required permissions for the release workflow.
Refs: https://github.com/heroku/buildpacks-jvm/pull/389, GUS-W-11937667
=> Fix permissions for release workflow

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/src/main.rs, test_support/src/lib.rs
This is a fix against the changes introduced with [#373](https://github.com/heroku/buildpacks-nodejs/pull/373) where the use of `npx` was not detecting the runtime command (`sf-fx-runtime-nodejs`) already installed globally.
The effect of which was the runtime would be downloaded when the Function application initially starts up which is not ideal since it causes slower boot times + may cause non-deterministic behavior.
[W-11854639](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE000017vsgyYAA/view?ws=%2Flightning%2Fr%2FADM_Epic__c%2Fa3QEE000000MuDF2A0%2Fview)
=> fix: use the proper command path for local/global runtime

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/src/bin/web_env.rs
Fixes #210. If `WEB_CONCURRENCY` is set, the buildpack shouldn't change the value.
[W-11985938](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00001B8AjcYAF)
=> Don't overwrite WEB_CONCURRENCY with a different value

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml
Updates the buildpack to use the `0.14.0` version of the node function runtime for functions that still rely on the implicit dependency.
=> Update `sf-fx-runtime-nodejs` from 0.12.0 to 0.14.0

Cargo.lock, Cargo.toml, buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-corepack/README.md, buildpacks/nodejs-corepack/build.sh, buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-corepack/package.toml, buildpacks/nodejs-corepack/src/cfg.rs, buildpacks/nodejs-corepack/src/cmd.rs, buildpacks/nodejs-corepack/src/errors.rs, buildpacks/nodejs-corepack/src/layers/manager.rs, buildpacks/nodejs-corepack/src/layers/mod.rs, buildpacks/nodejs-corepack/src/layers/shim.rs, buildpacks/nodejs-corepack/src/main.rs, buildpacks/nodejs-corepack/tests/integration_test.rs, buildpacks/nodejs-yarn/src/main.rs, common/nodejs-utils/src/package_json.rs, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml, test/specs/node/cutlass/basic_spec.rb, test_support/src/lib.rs
This PR adds a `heroku/nodejs-corepack` buildpack. A full description of the buildpacks functionality is available in the [README](https://github.com/heroku/buildpacks-nodejs/blob/corepack/buildpacks/nodejs-corepack/README.md). For now, the corepack buildpack will only install `yarn` (though corepack can install `pnpm` and `npm`).
There are also changes to the yarn buildpack -- it will no longer install `yarn` if it's already installed (otherwise, `heroku/nodejs-corepack` + `heroku/nodejs-yarn` would result in two `yarn` installations.
The yarn use case is the primary reason for adding this, but the design should allow adding `pnpm` and `npm` support later without too much trouble.
[W-12131343](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00001F2GFiYAN)
=> Add heroku/nodejs-corepack leveraging libcnb.rs

.github/workflows/release.yml
`heroku/nodejs-corepack` is intended to be published to dockerhub. This repository has no other dockerhub buildpacks, so dockerhub login needs to be added prior to publishing.
=> Support publishing images to dockerhub

Cargo.toml, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-yarn/Cargo.toml, buildpacks/nodejs-yarn/src/main.rs, common/nodejs-utils/Cargo.toml, test_support/Cargo.toml
Some PRs are failing CI due to clippy issues on rust 1.67 ([this one](https://github.com/heroku/buildpacks-nodejs/actions/runs/4062621370/jobs/6993899601) for example). This PR updates all crates to rust 1.67 and fixes the clippy issue. This also changes several common cargo settings to be shared across all crates in the repo.
=> Update all crates to Rust 1.67

buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-yarn/CHANGELOG.md, common/nodejs-utils/src/package_json.rs
It looks like `name` could be optional for packages that aren't intended to be published: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#name
Resolves #371.
=> Make package.json's `name` field optional

buildpacks/nodejs-corepack/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
The last release automation for heroku/nodejs-corepack failed silently (https://github.com/heroku/buildpacks-nodejs/actions/runs/3941678312/jobs/6744391908) due to improper configuration, so the version was never incremented. This should fix that issue so that the next release works properly.
Additionally, nodejs-corepack was not included in the last heroku/nodejs release. This should fix that as well.
=> Fixup nodejs-corepack for release

.github/workflows/inventory.yml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/README.md, buildpacks/nodejs-yarn/inventory.toml, buildpacks/nodejs-yarn/src/layers/cli.rs, buildpacks/nodejs-yarn/src/main.rs, common/nodejs-utils/src/nodebin_s3.rs, test/fixtures/yarn-2-modules-nonzero/package.json, test/fixtures/yarn-3-modules-zero/package.json
This will make newer "berry" releases of Yarn (versions 2.x, 3.x, and 4.x) available for installation.
A few additional notes:
- To preserve backwards compatibility and match github.com/heroku/heroku-buildpack-nodejs, we default to yarn `1.22.x` if no version range is provided.
- The name of the first level directory in the archive is different depending on what yarn version was mirrored. There's a new conditional to address this.
- Some yarn berry releases don't have the entrypoint set as executable. This PR addresses that by manually setting permissions to `0755`.
- This also adds automation for yarn inventory updates, exactly like we have for Node releases already.
[W-12400621](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00001JdaBYYAZ)
=> Make Yarn 2+ CLI versions available for install

meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
The `heroku/nodejs` and `heroku/nodejs-function` meta buildpacks are using a very old buildpack API version, which throws deprecation errors with newer lifecycle versions. 
This PR brings the buildpack api version up to date with the non-meta buildpacks in this project.
[W-12541151](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00001LFa2GYAT)
=> Bump meta buildpacks to buildpack API 0.9

Cargo.toml, common/nodejs-utils/Cargo.toml
When compiling release binaries, we should strip them. This will keep them small, which is especially useful for cases like https://github.com/heroku/heroku-buildpack-nodejs/pull/1061, where the compiled binary is part of the repo.
The other crates in this repo are buildpacks, which are compiled with libcnb.rs, which already enforces stripping.
=> Strip nodejs-utils binaries

Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/src/function.rs, buildpacks/nodejs-yarn/Cargo.toml, common/nodejs-utils/Cargo.toml
Updating libcnb-test and toml at the same time to prevent conflicts. This also required a libherokubuildpack update. Supersedes #485 and #471.
=> Update libcnb-test and toml

.github/workflows/release.yml
Release workflows are failing due to IP whitelisting, for example: https://github.com/heroku/buildpacks-nodejs/actions/runs/4600643908. This puts the release workflow on private runners.
=> Use private runner for release workflow

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/buildpack.toml, meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs-function/buildpack.toml, test/meta-buildpacks/nodejs/buildpack.toml
Usually, these changes would have been automated PRs. However, they were missed since both https://github.com/heroku/buildpacks-nodejs/actions/runs/4600643908/jobs/8127500398 and https://github.com/heroku/buildpacks-nodejs/actions/runs/4600648025/jobs/8127509886 failed on IP whitelisting issues.
Note that the IP whitelisting issues should be fixed in the future thanks to #487.
=> Post release updates heroku/nodejs-engine 0.8.17, heroku/nodejs-yarn 0.4.1

.github/workflows/ci.yml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml, test/meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs/package.toml
This will allow `heroku/nodejs` to detect and build corepack apps.
Related: 
- #488 
- #489 
[W-13055295](https://gus.my.salesforce.com/one/one.app#/alohaRedirect/a07EE00001PifhGYAR)
=> Add a pnpm group to heroku/nodejs

buildpacks/nodejs-corepack/tests/integration_test.rs, test/fixtures/pnpm-7-pnp/package.json, test/fixtures/pnpm-8-hoist/package.json
Versions of `pnpm` released prior to the Node.js 20 release are not compatible with Node.js 20.x. This incompatibility is causing all of our `pnpm` integration tests to fail. This PR updates the pnpm 8 fixture to use the Node.js 20.x compatible version of pnpm, and locks the pnpm 7 fixture to Node.js 18.
Example CI failure that this fixes: https://github.com/heroku/buildpacks-nodejs/actions/runs/4850258691/jobs/8782159932?pr=515#step:8:336
=> Update to latest pnpm releases in fixtures

buildpacks/nodejs-pnpm-install/tests/integration_test.rs
When appropriate, `pnpm` emits a new version notification warning like this:
```
╭─────────────────────────────────────────────────────────────────╮
│                                                                 │
│                Update available! 7.32.3 → 8.4.0.                │
│   Changelog: https://github.com/pnpm/pnpm/releases/tag/v8.4.0   │
│     Run \"corepack prepare pnpm@8.4.0 --activate\" to update.   │
│                                                                 │
│     Follow @pnpmjs for updates: https://twitter.com/pnpmjs      │
│                                                                 │
╰─────────────────────────────────────────────────────────────────╯
```
However, this is an async process, so the location of this line in the build log may change. This …
=> Split up pnpm text assertions

.github/workflows/ci.yml, buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-pnpm-install/CHANGELOG.md, buildpacks/nodejs-pnpm-install/buildpack.toml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/README.md, buildpacks/npm/buildpack.toml
The `heroku-18` stack is now EOL, as documented [here](https://help.heroku.com/X5OE6BCA/heroku-18-end-of-life-faq). It no longer makes sense for these buildpacks to support `heroku-18`.
=> Drop references to heroku-18

.github/workflows/release.yml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml, meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, test/meta-buildpacks/nodejs-function/buildpack.toml
Updates all buildpacks to be published in Docker Hub (instead of our AWS ECR). 
This PR does not change any `package.toml` references to published buildpacks - that will occur as the part of the buildpack release process.
This is a prerequisite of sorts for https://github.com/heroku/buildpacks-nodejs/pull/524. That PR wants to use AWS credentials for S3 binary mirroring, but we're already using AWS credentials for publishing to ECR. This change should free up of AWS credentials, so the other PR doesn't have to deal with scoping credentials.
=> Change all buildpack registries to dockerhub

.github/workflows/ci.yml
The integration tests are so slow... something must be done!
This PR changes the libcnb.rs integration test job to a matrix -- one job for each libcnb.rs buildpack, each of which uses a bigger instance.
This improves CI runtime from around 20 minutes to around 8 minutes.
Inspired largely by @Malax's work in https://github.com/heroku/buildpacks-jvm/pull/478.
=> Optimize CI integration tests for runtime

meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
The last meta-buildpack release actions (https://github.com/heroku/buildpacks-nodejs/actions/runs/5049524949 and https://github.com/heroku/buildpacks-nodejs/actions/runs/5049523935) timed out due to instance queuing delays on the CNB side. The CNB releases eventually went out, but the rest of our release automation failed. This PR finishes up that process for `heroku/nodejs` and `heroku/nodejs-function`.
=> Post-release updates: heroku/nodejs@0.6.5, heroku/nodejs-function@0.10.5

buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-function-invoker/tests/integration_test.rs, test/specs/node-function/cutlass/function_spec.rb
Building Salesforce Functions on the heroku-20 stack has been disabled in the following ways:
- All Salesforce Function builds happen on `heroku-22` only since last September: https://developer.salesforce.com/docs/platform/functions/guide/release-notes-intro.html#september-28-2022
- Function buildpacks were pulled from the `heroku/buildpacks:20` builder a few weeks ago: https://github.com/heroku/builder/pull/338
Therefore, it doesn't make sense to support `heroku-20` for the `heroku/nodejs-function` and `heroku/nodejs-function-invoker` buildpacks going forward. 
Node.js Salesforce Functions on `heroku-22` remain supported and otherwise unchanged.
=> Drop heroku-20 support for Node.js Salesforce Functions

common/nodejs-utils/src/distribution.rs
The new mirroring logic introduced in #524 is not mirroring the Yarn 4+ release candidates. This is due to a particularity in node-semver's resolution mechanics, explained here: https://github.com/npm/node-semver#prerelease-tags.
Basically, to have a prerelease satisfy a requirement, the requirement needs to specify that exact major, minor, patch and prerelease tag.
This PR expands what we view as mirrorable to include Yarn 4 release candidates. These release candidates are already in the inventory (see them [here](https://github.com/heroku/buildpacks-nodejs/blob/2730256fadf2c94dae6813dfc672065da9b406ce/buildpacks/nodejs-yarn/inventory.toml#L861C13-L877)), so we should continue to mirror them.
=> Update active yarn versions to include Yarn 4 release candidates

common/nodejs-utils/src/distribution.rs
In #537, I adjusted the version requirement for active versions of yarn. But, the semver parser handled the invalid `>= 1.22 >=4.0.0-rc.40` syntax by disregarding the first half, and using only `>=4.0.0-rc.40` half. So the mirroring logic was missing yarn versions less than 4 for a brief time. The problem was a missing `||` operator. I've also added some tests to make sure it's working correctly.
=> Fix yarn active version calculation

.github/workflows/inventory.yml
In #550, there is an extra dash in the changelog. This will fix the automation so there will only be one dash on the next inventory update.
=> Drop the extra dash in the inventory changelog

Cargo.lock, buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-function-invoker/opt/nodejs-runtime.sh, buildpacks/nodejs-function-invoker/src/layers/mod.rs, buildpacks/nodejs-function-invoker/src/layers/script.rs, buildpacks/nodejs-function-invoker/src/main.rs, buildpacks/nodejs-pnpm-install/CHANGELOG.md, buildpacks/nodejs-pnpm-install/Cargo.toml, buildpacks/nodejs-pnpm-install/buildpack.toml, buildpacks/nodejs-pnpm-install/src/main.rs, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/Cargo.toml, buildpacks/nodejs-yarn/buildpack.toml, buildpacks/nodejs-yarn/src/main.rs, test_support/Cargo.toml
This updates all libcnb.rs buildpacks to Buildpack API 0.9, and brings libcnb.rs up to date for each.
The changes to `ProcessBuilder` shown here are explained upstream: https://github.com/heroku/libcnb.rs/releases/tag/v0.12.0
The new `direct = true` default was incompatible with the heroku/nodejs-function-invoker buildpack. It was using bash-interpolated arguments (notably `${PORT:-8080}`), so doesn't work in `direct = true` mode. I added a layer with a bash script to do that work. It nearly mirrors what the JVM equivalent does here: https://github.com/heroku/buildpacks-jvm/blob/main/buildpacks/jvm-function-invoker/src/layers/opt.rs.
=> Buildpack API 0.9 + libcnb.rs updates

.github/workflows/inventory.yml
This reverts commit 6728b1662193f2a114a3b7b274a8425d2c31f67d. The change in #556 didn't work, since https://github.com/heroku/use-app-token-action is private. Failed run: https://github.com/heroku/buildpacks-nodejs/actions/runs/5245698173.
=> Revert "Create automated PR with token (#556)"

.github/workflows/inventory.yml
Generates a token from a GitHub app that can be used in automation tasks that create pull requests.
This is a redo of #556 which initially failed because [heroku/use-app-token-action](https://github.com/heroku/use-app-token-action) was a private action and those can't be used with public repositories.  The action is now public so this shouldn't be a problem anymore.
=> Create automated PR with token

common/bin/download-verify-npm-package
When listing the upstream yarn distributions there is a version `2.4.3` which is tagged as `berry` in npm for the `yarn` package (https://www.npmjs.com/package/yarn/v/2.4.3).
Our mirroring automation expects yarn versions > 1.x to be distributed under the `@yarnpkg/cli-dist` but there is no published package for `@yarnpkg/cli-dist@2.4.3`.
This change should fix our Yarn mirroring which appears broken in GitHub Action runs due to version `2.4.3` belonging to the `yarn`, not `@yarnpkg/cli-dist`.
=> Support yarn 2.4.3

common/bin/download-verify-npm-package, common/nodejs-utils/src/distribution.rs
After [#617](https://github.com/heroku/buildpacks-nodejs/pull/617) was merged our inventory automation ran and the PR to update the `yarn` inventory with `2.4.3` ([#620](https://github.com/heroku/buildpacks-nodejs/pull/620)) had failing tests that showed that the layout for this version did not match our other distributions.
This PR modifies the automation to ignore this version of `yarn` so that our mirroring jobs no longer report as failing and we will not get this distribution added to our inventory since it requires special handling in the buildpack to be usable.
This was the preferred alternative to #626.
=> Ignore yarn 2.4.3

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml
Since there has been a new Procfile CNB release:
https://github.com/heroku/procfile-cnb/releases/tag/v2.0.1
https://github.com/heroku/procfile-cnb/compare/v2.0.0...v2.0.1
Also switches the buildpack URI to using the image SHA256, for parity with the URI used in `heroku/builder`.
GUS-W-13982692.
=> Update Procfile CNB to v2.0.1

.gitignore, Cargo.lock, Cargo.toml, README.md, buildpacks/nodejs-corepack/tests/integration_test.rs, buildpacks/nodejs-engine/tests/integration_test.rs, test_support/src/lib.rs
Updates libcnb related crates from 0.13.0 to 0.14.0:
https://github.com/heroku/libcnb.rs/releases/tag/v0.14.0
Dependabot didn't open a PR since it appears to have issues with Cargo workspace root dependencies when using the beta dependency grouping feature. (I'll report this upstream shortly)
I've also updated the `nodejs-corepack` integration tests to use the improved `run_shell_command` helper - which is a much better fit for running one off commands. (This helper existed before, but as of libcnb 0.14.0 now offers even more advantages, since it's able to validate exit code.)
GUS-W-13976470.
=> Update to libcnb 0.14.0

.github/workflows/_mirror-distribution.yml
Prevents the `mirror-distribution` from running when the versions output is an empty JSON array. Otherwise, the strategy evaluator will fail with:
```
Error when evaluating 'strategy' for job 'mirror-distribution'. heroku/buildpacks-nodejs/.github/workflows/_mirror-distribution.yml@d2b2e4b41bd74186941b08ae182261ac87ff5187 (Line: 49, Col: 18): 
Matrix vector 'version' does not contain any values
```
=> Skip `mirror-distribution` job if there are no versions

common/bin/download-verify-npm-package
The changes to make this download script work for both `npm` and `yarn` distributions [#612](https://github.com/heroku/buildpacks-nodejs/pull/612) has a bug where the requested distribution (`yarn`) differs from its package name if the version is `>=2` (`@yarnpkg/cli-dist`) and that wasn't accounted for in the name of the download file.
The `curl` command that downloads the tarball should have been saving to `yarn-v{x.y.z}.tar.gz` but was instead saving to `@yarnpkg/cli-dist-v{x.y.z}.tar.gz`. This is causing automation failures (e.g.; https://github.com/heroku/buildpacks-nodejs/actions/runs/6179740345/job/16775160336)
This PR keeps the `distribution_name` and `package_name` separate so this mismatch will no longer happen.
It also:
- adds some extra logging which would have made the error …
=> Fix downloads for @yarnpkg/cli-dist

Cargo.lock, Cargo.toml, buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-corepack/src/main.rs, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/lib.rs, common/nodejs-utils/src/telemetry.rs
This adds an `initTracer` function for Node.js buildpacks to use, which sets up an OpenTelemetry file exporter for tracing data. 
Additionally, this adds some tracing to the`heroku/nodejs-corepack` buildpack.
=> Add otel tracing via file exports to nodejs-corepack

buildpacks/nodejs-engine/tests/integration_test.rs, test/specs/node-function/spec_helper.rb, test/specs/node/cutlass/basic_spec.rb, test/specs/node/spec_helper.rb, test_support/src/lib.rs
Since the `heroku/buildpacks:20` image is about to be deprecated, and has been replaced by the newly added `heroku/builder:20` for those that need to use a Heroku-20 based builder.
The build and run images used by `heroku/builder:20` are the same as those used by `heroku/buildpacks:20` - the only differences between the builders are the included buildpacks (which is somewhat irrelevant for these integration tests, since the buildpack under test will be injected instead).
The smoke tests in the `heroku/builder` GitHub repo are still testing against all image variants (until such time as we make the legacy images error with an EOL message), so we still have test coverage against them.
See:
https://github.com/heroku/builder/pull/394
https://salesforce.quip.com/0JtbAYiWZYk6
GUS-W-14186015.
=> Switch tests from `heroku/buildpacks:20` to `heroku/builder:20`

buildpacks/nodejs-pnpm-install/README.md
There is no such builder `heroku/buildpacks:22` - the correct Docker image name is `heroku/builder:22`.
See:
https://github.com/heroku/cnb-builder-images/blob/main/README.md
https://hub.docker.com/r/heroku/builder/tags
=> Fix non-existent builder Docker image name

buildpacks/nodejs-corepack/README.md
The previous link was missing the `heroku/` segment, so 404ed.
The repo has also just been renamed, in:
https://github.com/heroku/cnb-builder-images/issues/396
GUS-W-14201543.
=> Fix CNB builder repo URL

.github/workflows/ci.yml, Cargo.lock, buildpacks/nodejs-corepack/tests/integration_test.rs, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-function-invoker/src/main.rs, buildpacks/nodejs-function-invoker/tests/integration_test.rs, buildpacks/nodejs-pnpm-install/tests/integration_test.rs, buildpacks/nodejs-yarn/tests/integration_test.rs, test_support/Cargo.toml, test_support/src/lib.rs
Removes the double tests that were added in several integration suites that would explicitly run against the `20` and `22` stacks and updates the CI workflow to control this.
This also leverages `libcnb@0.15.0` to run our integration tests against the composite buildpacks (`heroku/nodejs` and `heroku/nodejs-function`) so the build order/grouping matches what the user would see instead of manually defining individual buildpacks in tests.
=> Prepare integration tests to run under a single builder

buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-npm-engine/CHANGELOG.md, buildpacks/nodejs-npm-engine/buildpack.toml, buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/buildpack.toml, buildpacks/nodejs-pnpm-install/CHANGELOG.md, buildpacks/nodejs-pnpm-install/buildpack.toml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/buildpack.toml, buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml, meta-buildpacks/nodejs-function/CHANGELOG.md, meta-buildpacks/nodejs-function/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
Adjusts the buildpack `name`, `description` and `keywords` in the `buildpack.toml` of all buildpacks to match the style discussed in:
https://github.com/heroku/cnb-builder-images/issues/408
These fields are used by the CNB registry and can also be seen in the output of `pack builder inspect`. They are not used by `pack build` or Kodon. In addition to standardising the metadata, one of the objectives here is to ensure users don't accidentally use component buildpacks when they really wanted the composite buildpack.
The `keywords` field has intentionally been omitted from the functions buildpacks since they are EOL and so don't want to be made more discoverable. (The CNB registry doesn't currently ingest/display the keywords currently, but may in the future.)
In addition, I've marked the …
=> Update buildpack metadata in buildpack.toml

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml, meta-buildpacks/nodejs/package.toml
Previously the `heroku/procfile` buildpack was included within the `heroku/nodejs` composite buildpack.
Whilst this is convenient (it saves having to add the Procfile CNB manually), this approach has a number of issues:
- If an app uses multiple languages (eg `heroku/nodejs` and `heroku/java`), the Procfile CNB will end up being run multiple times, and potentially with different versions of the Procfile buildpack.
- It means multiple places need updating after Procfile CNB releases, and means the builder image can end up containing several different versions of the Procfile buildpack.
After this change, the `heroku/procfile` CNB is no longer included in the `heroku/nodejs` composite buildpack, and instead will be included in the Heroku builder image order grouping (added in the PR that …
=> Remove `heroku/procfile` from `heroku/nodejs`

meta-buildpacks/nodejs/CHANGELOG.md
The composite buildpack `heroku/nodejs` should have had entries added for the new npm buildpacks merged in PRs:
- #623
- #625
- #685
=> Added missing changelog entries for npm buildpacks

buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/inventory.toml
This reverts commit 64ec7dbe296d21dc937e68d38b8b3f4e2cef7c7b (#691).
In my own testing, yarn 4 builds aren't working properly. Example failure: https://github.com/heroku/buildpacks-nodejs/actions/runs/6629679100/job/18009505103?pr=698. I think this is because yarn 4 defaults `enableGlobalCache` to `true`.
=> Remove yarn 4.0.0 from inventory

Cargo.toml
To resolve (pun intended) this Cargo resolver version deprecation warning:
```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
```
Fixes #701.
=> Set explicit `resolver` version in workspace Cargo.toml

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs
As of [2023-10-24](https://github.com/nodejs/node/blob/main/doc/changelogs/CHANGELOG_V20.md#2023-10-24-version-2090-iron-lts-richardlau), Node.js 20.x is now the LTS version.  Previously, this buildpack would default to the latest known Node.js release if one was not provided. Now it will default to the latest Active LTS version.
[W-14390764](https://gus.lightning.force.com/lightning/r/a07EE00001dS3sgYAC/view)
=> Update default Node version to 20.x

buildpacks/npm/CHANGELOG.md, buildpacks/npm/buildpack.toml
Since Buildpack API 0.6 has been deprecated for some time, and is no longer supported by newer versions  of `lifecycle`, which is causing CI to fail since the integration tests in this repo use `heroku/builder:22`, which has just had its lifecycle version upgraded:
https://github.com/heroku/cnb-builder-images/pull/431
These CI failures are not reflective of production (which is working fine), since Functions in production are actually run via the functions builder image (and not `heroku/builder:22`), which was intentionally left on the old lifecycle version. However, this functions builder image is not available on Docker Hub, so can't be used by the integration tests in this repo.
Improving parity of the integration tests here might be worth considering longer term, however, upgrading …
=> Update the legacy NPM buildpack to Buildpack API 0.7

Cargo.lock, Cargo.toml, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-engine/src/layers/npm_engine.rs, buildpacks/nodejs-npm-engine/src/main.rs, buildpacks/nodejs-npm-engine/src/node.rs, buildpacks/nodejs-npm-engine/src/npm.rs, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-npm-install/src/errors.rs, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-npm-install/src/npm.rs
Since the feature branch no longer exists.
This will fix Dependabot erroring out with:
```
Errored with the message "Dependabot couldn't fetch the branch/reference for commons"
```
This also required adding `fun_run` as an explicit dependency, due to:
https://github.com/heroku/buildpacks-ruby/pull/232
=> Switch to consuming `commons` from the Ruby CNB `main` branch

Cargo.toml, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-pnpm-install/Cargo.toml, buildpacks/nodejs-yarn/Cargo.toml, common/nodejs-utils/Cargo.toml, test_support/Cargo.toml
Both Dependabot and `cargo-edit`'s `cargo upgrade` don't seem to handle dependencies being specified in the Cargo workspace `Cargo.toml` and inherited by individual crates very well.
As such, this switches back to specifying those dependencies explicitly in each crate. Dependabot always updates dependencies across all crates, so they will still stay in sync.
This will unblock Dependabot being able to open a PR for libcnb 0.16.0.
See also:
https://github.com/heroku/buildpacks-jvm/pull/614
I've left the local shared crate dependencies as workspace-defined, since Dependabot or `cargo-edit` doesn't need to update those, since they are path-only dependencies.
Lastly, the lists of dependencies have been sorted alphabetically.
GUS-W-14513796.
=> Switch away from workspace-defined dependencies

Cargo.toml, buildpacks/nodejs-corepack/src/main.rs, buildpacks/nodejs-engine/src/bin/web_env.rs, buildpacks/nodejs-engine/src/layers/dist.rs, buildpacks/nodejs-engine/src/layers/mod.rs, buildpacks/nodejs-engine/src/layers/web_env.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-function-invoker/src/function.rs, buildpacks/nodejs-function-invoker/src/layers/runtime.rs, buildpacks/nodejs-function-invoker/src/layers/script.rs, buildpacks/nodejs-function-invoker/src/main.rs, buildpacks/nodejs-function-invoker/tests/integration_test.rs, buildpacks/nodejs-npm-engine/src/main.rs, buildpacks/nodejs-npm-engine/tests/integration_test.rs, buildpacks/nodejs-npm-install/src/errors.rs, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-npm-install/tests/integration_test.rs, buildpacks/nodejs-pnpm-install/src/main.rs, buildpacks/nodejs-yarn/src/layers/cli.rs, buildpacks/nodejs-yarn/src/main.rs, clippy.toml, common/nodejs-utils/src/application.rs, common/nodejs-utils/src/distribution.rs, common/nodejs-utils/src/inv.rs, common/nodejs-utils/src/package_manager.rs, common/nodejs-utils/src/s3.rs, common/nodejs-utils/src/vrs.rs, test_support/src/lib.rs
Enables some off-by-default lints that we already use in the `libcnb.rs` repository.
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unreachable-pub
https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html#unsafe-code
https://rust-lang.github.io/rust-clippy/master/index.html#/panic_in_result_fn
https://rust-lang.github.io/rust-clippy/master/index.html#/unwrap_used
GUS-W-14523836.
=> Enable additional rustc and Clippy lints

buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-npm-install/tests/integration_test.rs
This change prevents the detection routine from raising an error during detect if:
- there is no `package.json`
- there is a `package.json` but it cannot be read for some reason
Both error cases will be handled and report a failed detect.  
Fixes #722
=> Gracefully handle error when trying to read `package.json` in detect

Cargo.toml, buildpacks/nodejs-corepack/Cargo.toml, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-function-invoker/Cargo.toml, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-pnpm-engine/Cargo.toml, buildpacks/nodejs-pnpm-install/Cargo.toml, buildpacks/nodejs-yarn/Cargo.toml, common/nodejs-utils/Cargo.toml, test_support/Cargo.toml
As of Cargo 1.75 the `version` property in `Cargo.toml` is now optional, and if omitted is the same as having specified `version = "0.0.0"` and `publish = false`:
https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-175-2023-12-28
https://doc.rust-lang.org/cargo/reference/manifest.html#the-version-field
Therefore for crates that we do not publish, we can now remove both the `version` and `publish` properties, avoiding the need for the fake `0.0.0` version that differs from the actual buildpack version in `buildpack.toml`.
In addition, the `Cargo.toml` `description` property has been removed, since:
- it's unused unless the crate is published
- it duplicates the description in `buildpack.toml` / the README etc
GUS-W-14821120.
=> Simplify Cargo metadata for `publish = false` crates

.github/CODEOWNERS
This modification to the `CODEOWNERS` file is based off suggestions from @edmorley to help reduce review notification overload for the team.
For most PRs, the Languages team will be requested for review except for automation-based changes which are assigned to specific language owners since they often require further action such as performing a release, etc.
=> Update CODEOWNERS to reduce review notification noise

.github/workflows/ci.yml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/node_runtime_metrics/metrics_collector.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/clustered_app.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/fixtures/worker_threads_app.cjs, buildpacks/nodejs-engine/node_runtime_metrics/test/metrics.spec.cjs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs, common/nodejs-utils/src/vrs.rs
To support earlier Node.js version several adjustments needed to be made to the metrics script. These include:
- dropping the `node:` protocol from required core modules
- using `http` instead of `fetch`
- using API signatures compatible across all versions:
- `PerformanceObserver.observe`
- `PerformanceEntry.kind` vs. `PerformanceEntry.detail.kind`
- `cluster.isPrimary` vs. `cluster.isMaster`
This PR also includes changes to the CNB to restrict the layer containing the metrics script to only versions of Node `>=14.10`.
[W-14838686](https://gus.lightning.force.com/lightning/r/a07EE00001iPnjsYAC/view)
Fixes #754
=> Update metrics scripts to be compatible with Node v14.10.+

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/src/bin/web_env.rs
This allows the WEB_MEMORY / WEB_CONCURRENCY selection to be more appropriate on memory heavy instances. This mirrors the work in https://github.com/heroku/heroku-buildpack-nodejs/pull/1196.
[GUS](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001g8anxYAA/view)
=> Adjust WEB_CONCURRENCY calculations for memory heavy instances

Cargo.lock
Dependabot is [currently failing](https://github.com/heroku/buildpacks-nodejs/network/updates/794480345) since it doesn't like the fact that the version of the Ruby `commons` module (which is imported via a GitHub URL) has changed from `1.0.0` to `0.0.0` after:
https://github.com/heroku/buildpacks-ruby/pull/248
To fix this the lockfile entry for `commons` needs regenerating.
However, whilst I'm here I've just regenerated the whole lockfile, to pick up any other in-range version updates.
=> Fix/regenerate Cargo.lock

CODE_OF_CONDUCT.md, SECURITY.md
`CODE_OF_CONDUCT.md` and `SECURITY.md` are missing. This imports them from https://github.com/salesforce/oss-template.
=> Add Salesforce standard OSS Docs

buildpacks/nodejs-engine/tests/integration_test.rs, test_support/src/lib.rs
Several of the metrics tests are temporal-based and, while we can get decent reliability by tweaking the timeouts used, it's not a guarantee that the chosen timeouts will always be effective which can lead to unwanted flakiness during test runs or test runs that wait longer than necessary.
To balance the tradeoff between wait time and test execution time, this PR introduces `wait_for(condition, timeout)` which will continually poll the state of the given `condition` until it passes or the `timeout` is exceeded. This should help to minimize the wait time required to guarantee the expected outcome.
=> Fix flaky integration tests

.github/workflows/inventory.yml, Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/inventory.toml, buildpacks/nodejs-engine/src/layers/dist.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/bin/update_node_inventory.rs, common/nodejs-utils/src/lib.rs, common/nodejs-utils/src/vrs.rs
This PR introduces support for the artifact inventory code shared with the Go buildpack, and updates the GitHub actions for node.js to write a corresponding `inventory.toml` file in the new format (which includes the `sha256` checksum that is used to verify the download, as well as the upstream URL rather than our own S3 mirrored artifact store).
A few notes:
* The shared inventory code is being [pulled directly from the Go buildpack](https://github.com/heroku/buildpacks-nodejs/pull/814/files#diff-1c40ca553da3605cd6bc186c75dc58896ae0e0114a1bb8479939b219747d3117R10). This will be moved to `libherokubuildpack` at some point.
* The inventory file includes arm64 and amd64 linux artifacts and are resolved based on [the current host OS and …
=> Use artifact inventory

buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/buildpack.toml, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/buildpack.toml, buildpacks/nodejs-function-invoker/CHANGELOG.md, buildpacks/nodejs-function-invoker/buildpack.toml, buildpacks/nodejs-npm-engine/CHANGELOG.md, buildpacks/nodejs-npm-engine/buildpack.toml, buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/buildpack.toml, buildpacks/nodejs-pnpm-engine/CHANGELOG.md, buildpacks/nodejs-pnpm-engine/buildpack.toml, buildpacks/nodejs-pnpm-install/CHANGELOG.md, buildpacks/nodejs-pnpm-install/buildpack.toml, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/buildpack.toml, meta-buildpacks/nodejs/CHANGELOG.md
This PR simply adds the linux/arm64 targets required to package and use the various buildpacks in this repository.
It depends on https://github.com/heroku/buildpacks-nodejs/pull/814, which introduces arm64 support through updated inventory logic and version resolution that factors in the host OS and arch.
=> Add linux/arm64 targets

meta-buildpacks/nodejs/CHANGELOG.md, meta-buildpacks/nodejs/buildpack.toml
We haven't added `[[metadata.targets]]` to `heroku/nodejs` yet, so it will be published as single architecture. Adding that here and updating the changelog to match reality.
=> Add `[[metadata.targets]]` to `heroku/nodejs` for arm64 support

buildpacks/nodejs-pnpm-install/tests/integration_test.rs
Removed the check for empty `stderr` output which started failing because the following message is now emitted on install of the `browserlist` package:
```
WARN  Browserslist: caniuse-lite is outdated. Please run:
npx update-browserslist-db@latest
Why you should do it regularly: https://github.com/browserslist/update-db#readme
```
See https://github.com/heroku/buildpacks-nodejs/actions/runs/9185177895/job/25258708325?pr=846
=> Fix failing integration test

.github/workflows/ci.yml
Smaller runners are more plentiful, and we no longer need to install Docker, either!
=> Use pub-hk-ubuntu-22.04-arm-small

.github/workflows/ci.yml
libc-dev and Rust are already on the base image
Follow-up to #852
=> Drop unnecessary installs for arm64 from workflow

.github/workflows/ci.yml
During the integration tests, if the application is started this will cause `pack` to download the run image if it hasn't already been pulled. Depending on how the tests are executed this could cause multiple attempts to download the run image. 
To be more respectful towards Docker pull limits, this PR attempts to pull the run image using metadata from the builder. This happens before the tests execute and only for tests that attempt to start the container so that pulls should be minimized.
=> Add CI step to docker pull the run image ahead of tests

.github/workflows/_mirror-distribution.yml, .github/workflows/_update-inventory.yml, .github/workflows/check_changelog.yml, .github/workflows/ci.yml, .github/workflows/inventory.yml
To update to Ubuntu 24.04, and to prevent the rate limit issues mentioned here:
https://github.com/heroku/buildpacks-go/pull/283
See also:
https://salesforce.quip.com/bu6UA0KImOxJ#temp:C:GZR57becb9df8d94f80b132168fd
https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2404-Readme.md
Closes #888.
GUS-W-16238120.
=> Switch to the new GitHub Actions runner groups

buildpacks/nodejs-engine/tests/integration_test.rs, buildpacks/nodejs-function-invoker/tests/integration_test.rs
The tests in this PR fail occasionally in CI test runs and then pass on re-run. I'm extending the timeouts in the hopes this will result in more stability.
=> Extend timeouts for test reliability

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/src/attach_runtime_metrics.rs, buildpacks/nodejs-engine/src/configure_web_env.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/fixtures/node-with-indexjs/index.js, buildpacks/nodejs-engine/tests/integration_test.rs, buildpacks/nodejs-npm-install/src/main.rs
As part of the migration to the new layer struct API (#880), the layer handler function names for `attach_runtime_metrics` and `configure_web_env` got reversed.
This should have been caught by integration tests but the tests that would exercise that area can be flaky due to timing issues. On further inspection, I realized that the intermittent failures I've seen recently weren't due to timing but because the `wait_for` function should only be used for checking positive signals (`assert_contains!`) and not negative signals (`assert_not_contains!`).
I've added extra logging so that these positive signals can be captured before checking for the absence of a message.
This PR also includes a small lint fix.
=> Fixed bug in `nodejs-engine` layer configuration

Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/install_node.rs, buildpacks/nodejs-engine/src/main.rs, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/bin/update_node_inventory.rs, common/nodejs-utils/src/vrs.rs
This PR removes the `heroku-inventory-utils` dependency in favor of the [recently migrated](https://github.com/heroku/libcnb.rs/pull/861) `inventory` code in `libherokubuildpack`.
=> Migrate to libherokubuildpack inventory

buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs
Node.js 22.x is now the Active LTS release line as of 10-29-2024 ([source](https://github.com/nodejs/Release)). In accordance with our support policy, it should be the default version.
=> Update default Node.js version to 22.x

README.md, buildpacks/nodejs-corepack/README.md, buildpacks/nodejs-pnpm-install/README.md
For multi-arch support + now that Heroku-24 is the default stack instead of Heroku-22.
=> Use `heroku/builder:24` in README usage instructions

buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-npm-install/tests/integration_test.rs, buildpacks/nodejs-pnpm-install/CHANGELOG.md, buildpacks/nodejs-pnpm-install/src/main.rs, buildpacks/nodejs-pnpm-install/tests/integration_test.rs, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/src/main.rs, buildpacks/nodejs-yarn/tests/integration_test.rs
This change treats the presence of a `Procfile` as the "source of truth" for how processes should be registered and will skip the default process registration that was previously performed for `npm`, `yarn`, and `pnpm`.
Fixes https://github.com/heroku/buildpacks-nodejs/issues/908
Related to https://github.com/heroku/buildpacks-go/pull/319
=> Skip default process registration when Procfile is present

Cargo.lock, buildpacks/nodejs-npm-engine/CHANGELOG.md, buildpacks/nodejs-npm-engine/Cargo.toml, buildpacks/nodejs-npm-engine/src/errors.rs, buildpacks/nodejs-npm-engine/src/install_npm.rs, buildpacks/nodejs-npm-engine/src/main.rs, buildpacks/nodejs-npm-install/CHANGELOG.md, buildpacks/nodejs-npm-install/Cargo.toml, buildpacks/nodejs-npm-install/src/configure_npm_cache_directory.rs, buildpacks/nodejs-npm-install/src/errors.rs, buildpacks/nodejs-npm-install/src/main.rs, buildpacks/nodejs-pnpm-engine/CHANGELOG.md, buildpacks/nodejs-pnpm-engine/Cargo.toml, buildpacks/nodejs-pnpm-engine/src/errors.rs, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/application.rs
Some of the buildpacks here were early adopters of the output module originally developed [in the Ruby buildpack](https://github.com/heroku/buildpacks-ruby/blob/221fe5bd5bfc5e2715e3810ce353a1252564f012/commons/src/output/mod.rs). This output module has been replaced by [bullet_stream](https://github.com/heroku-buildpacks/bullet_stream).
Eventually, all the buildpacks here will use [bullet_stream](https://github.com/heroku-buildpacks/bullet_stream). For now, I'm just migrating over the existing usage so that I no longer have to deal with errors like this:
https://github.com/heroku/heroku-buildpack-nodejs/actions/runs/12626267505/job/35179157027#step:4:24
=> Replace `commons` logger with `bullet_stream`

buildpacks/nodejs-corepack/CHANGELOG.md, buildpacks/nodejs-corepack/src/install_integrity_keys.rs, buildpacks/nodejs-corepack/src/main.rs
This is a workaround for Node versions that bundle a version of Corepack that is affected by recent changes to npm's public signing keys.
=> Update npm registry keys for Corepack

common/bin/download-verify-npm-package
This was broken by the recent addition of a secondary key to npm's list of public keys. This will unblock jobs like https://github.com/heroku/buildpacks-nodejs/actions/runs/13269889375/job/37046632436
=> Fix signing for npm inventory mirroring

Cargo.lock, buildpacks/nodejs-engine/Cargo.toml, buildpacks/nodejs-engine/src/install_node.rs, buildpacks/nodejs-engine/src/main.rs, buildpacks/nodejs-engine/tests/integration_test.rs
=> Update nodejs-engine buildpack output

.github/workflows/_mirror-distribution.yml, .github/workflows/_update-inventory.yml, .github/workflows/inventory.yml, .github/workflows/mirror.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml
As part of security-hardening our GHA workflows, this reduces the permissions granted to the automatically set `GITHUB_TOKEN` env var in GitHub Actions workflows to no more than what is required by that workflow.
See:
https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication
GUS-W-18053749.
=> Reduce scopes granted to `GITHUB_TOKEN` in GitHub Actions workflows

Cargo.lock, buildpacks/nodejs-pnpm-engine/CHANGELOG.md, buildpacks/nodejs-pnpm-engine/Cargo.toml, buildpacks/nodejs-pnpm-engine/src/errors.rs, buildpacks/nodejs-pnpm-engine/src/main.rs, buildpacks/nodejs-pnpm-engine/src/snapshots/errors___pnpm_engine_corepack_required_error.snap, buildpacks/nodejs-pnpm-engine/tests/integration_test.rs
This PR adds detailed and consistent error messages for the pnpm engine buildpack + includes snapshot testing for the output.
=> Improve pnpm engine errors

Cargo.lock, buildpacks/nodejs-yarn/CHANGELOG.md, buildpacks/nodejs-yarn/Cargo.toml, buildpacks/nodejs-yarn/src/cmd.rs, buildpacks/nodejs-yarn/src/configure_yarn_cache.rs, buildpacks/nodejs-yarn/src/errors.rs, buildpacks/nodejs-yarn/src/install_yarn.rs, buildpacks/nodejs-yarn/src/main.rs, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_build_script_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cache_get_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cli_layer_download_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cli_layer_installation_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cli_layer_permissions_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cli_layer_temp_file_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_cli_layer_untar_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_default_parse_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_deps_layer_create_cache_dir_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_deps_layer_yarn_cache_set_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_disable_global_cache_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_install_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_inventory_parse_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_node_build_scripts_metadata_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_package_json_access_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_package_json_parse_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_version_detect_yarn_version_command_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_version_detect_yarn_version_parse_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_version_resolve_error.snap, buildpacks/nodejs-yarn/src/snapshots/errors___yarn_version_unsupported_error.snap
This PR adds detailed and consistent error messages for the Yarn buildpack + includes snapshot testing for the output.
=> Improve Yarn errors

common/bin/download-verify-node
The signature file for verifying Node.js `v24.0.1` is missing from the release folder:
https://github.com/nodejs/node/issues/58249
This is currently blocking mirroring automation:
https://github.com/heroku/buildpacks-nodejs/actions/runs/14919465655/job/41911972459
=> Improve Node.js release verification script

.github/workflows/rebuild-snapshots.yml
This workflow can be used to rebuild and commit snapshots to a target branch. The trigger is manual so that any target branch can be chosen. Right now, I mostly need it for the Node.js release PRs (e.g.; #1109) but I anticipate situations where being able to run this workflow against other PRs might be useful.
=> Add workflow to rebuild snapshots

Cargo.lock, buildpacks/nodejs-engine/CHANGELOG.md, buildpacks/nodejs-npm-engine/CHANGELOG.md, buildpacks/nodejs-yarn/CHANGELOG.md, common/nodejs-utils/Cargo.toml, common/nodejs-utils/src/http.rs, common/nodejs-utils/src/lib.rs
Enables the [`rustls-tls-native-roots` feature of `reqwest`](https://docs.rs/reqwest/latest/reqwest/#optional-features) so that the [rusttls-native-certs](https://github.com/rustls/rustls-native-certs) crate will be used for TLS verification.
[W-19388322](https://gus.lightning.force.com/a07EE00002KTChQYAX)
=> Use OS certificate store for http requests

Cargo.lock, crates/xtask-update-nodejs-inventory/Cargo.toml
Using `crypto-rust` as the cryto backend for `sequoia-openpgp` (https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/openpgp#feature-flags). This requires also enabling `allow-experimental-crypto` and `allow-variable-time-crypto` as this backend is not appropriate for operations that require constant time but that's fine since we're just doing public key verification.
Without this PR, we'll get failures when running this tool without installing system packages (e.g.; https://github.com/heroku/buildpacks-nodejs/actions/runs/17799438910/job/50594959749).
=> Specify sequoia features to enable
